-- MySQL Script generated by MySQL Workbench
-- Wed Sep 27 13:05:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema maua_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maua_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maua_db` DEFAULT CHARACTER SET utf8 ;
USE `maua_db` ;

-- -----------------------------------------------------
-- Table `tb_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_usuarios` ;

CREATE TABLE IF NOT EXISTS `tb_usuarios` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(64) NOT NULL,
  `email_usuario` VARCHAR(128) NOT NULL,
  `senha_usuario` VARCHAR(256) NOT NULL,
  `categoria` TINYINT(4) NOT NULL DEFAULT 0,
  `data_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_cursos` ;

CREATE TABLE IF NOT EXISTS `tb_cursos` (
  `idcursos` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(64) NOT NULL,
  `coordenador_curso` VARCHAR(64) NOT NULL,
  `email_coordenador` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idcursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_alunos` ;

CREATE TABLE IF NOT EXISTS `tb_alunos` (
  `idaluno` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  `idcursos` INT(11) NOT NULL,
  `ra_aluno` INT(11) NOT NULL,
  PRIMARY KEY (`idaluno`),
  CONSTRAINT `fk_tb_alunos_tb_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `tb_usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_alunos_tb_cursos1`
    FOREIGN KEY (`idcursos`)
    REFERENCES `tb_cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_alunos_tb_usuarios_idx` ON `tb_alunos` (`idusuario` ASC);

CREATE INDEX `fk_tb_alunos_tb_cursos1_idx` ON `tb_alunos` (`idcursos` ASC);


-- -----------------------------------------------------
-- Table `tb_professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_professores` ;

CREATE TABLE IF NOT EXISTS `tb_professores` (
  `idprofessores` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idprofessores`),
  CONSTRAINT `fk_tb_professores_tb_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `tb_usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_professores_tb_usuarios1_idx` ON `tb_professores` (`idusuario` ASC);


-- -----------------------------------------------------
-- Table `tb_disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_disciplinas` ;

CREATE TABLE IF NOT EXISTS `tb_disciplinas` (
  `iddisciplina` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_disciplina` VARCHAR(45) NOT NULL,
  `nome_disciplina` VARCHAR(45) NOT NULL,
  `nome_coordenador` VARCHAR(64) NOT NULL,
  `email_coordenador` VARCHAR(128) NOT NULL,
  `semestralidade_disciplina` VARCHAR(45) NOT NULL,
  `serie_oferecida_d` TINYINT(4) NOT NULL,
  `serie_oferecida_n` TINYINT(4) NOT NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_notas` ;

CREATE TABLE IF NOT EXISTS `tb_notas` (
  `idnotas` INT(11) NOT NULL AUTO_INCREMENT,
  `iddisciplina` INT(11) NOT NULL,
  `p1` FLOAT NULL DEFAULT NULL,
  `p2` FLOAT NULL DEFAULT NULL,
  `ps1` FLOAT NULL DEFAULT NULL,
  `p3` FLOAT NULL DEFAULT NULL,
  `p4` FLOAT NULL DEFAULT NULL,
  `ps2` FLOAT NULL DEFAULT NULL,
  `t1` FLOAT NULL DEFAULT NULL,
  `t2` FLOAT NULL DEFAULT NULL,
  `t3` FLOAT NULL DEFAULT NULL,
  `t4` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idnotas`),
  CONSTRAINT `fk_tb_notas_tb_disciplinas1`
    FOREIGN KEY (`iddisciplina`)
    REFERENCES `tb_disciplinas` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_notas_tb_disciplinas1_idx` ON `tb_notas` (`iddisciplina` ASC);


-- -----------------------------------------------------
-- Table `tb_administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_administradores` ;

CREATE TABLE IF NOT EXISTS `tb_administradores` (
  `idadmin` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idadmin`),
  CONSTRAINT `fk_tb_administrador_tb_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `tb_usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_administrador_tb_usuarios1_idx` ON `tb_administradores` (`idusuario` ASC);


-- -----------------------------------------------------
-- Table `tb_recuperarsenhas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_recuperarsenhas` ;

CREATE TABLE IF NOT EXISTS `tb_recuperarsenhas` (
  `idrecuperar` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  `ip_maquina` VARCHAR(45) NOT NULL,
  `data_recuperacao` DATETIME NULL DEFAULT NULL,
  `data_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idrecuperar`),
  CONSTRAINT `fk_tb_recuperarsenha_tb_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `tb_usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_recuperarsenha_tb_usuarios1_idx` ON `tb_recuperarsenhas` (`idusuario` ASC);


-- -----------------------------------------------------
-- Table `tb_engenharia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_engenharia` ;

CREATE TABLE IF NOT EXISTS `tb_engenharia` (
  `iddisciplina` INT(11) NOT NULL,
  `idcursos` INT(11) NOT NULL,
  PRIMARY KEY (`iddisciplina`, `idcursos`),
  CONSTRAINT `fk_tb_disciplinas_has_tb_cursos_tb_disciplinas1`
    FOREIGN KEY (`iddisciplina`)
    REFERENCES `tb_disciplinas` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_disciplinas_has_tb_cursos_tb_cursos1`
    FOREIGN KEY (`idcursos`)
    REFERENCES `tb_cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_disciplinas_has_tb_cursos_tb_cursos1_idx` ON `tb_engenharia` (`idcursos` ASC);

CREATE INDEX `fk_tb_disciplinas_has_tb_cursos_tb_disciplinas1_idx` ON `tb_engenharia` (`iddisciplina` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
