<?php 

require_once('conexaoDB.php');

$body = file_get_contents('php://input');
$body = trim($body);
$obj = json_decode($body,true);

	$objDb = new db(); //instancio a classe para usar a função interna dela 
	$link = $objDb->conecta_mysql(); //função interna da classe db

	INSERIR CATEGORIA NA MAO 1 USUARIO DE CADA, GUARDAR NA SESSAO E VERIFICAR A CATEGORIA, PRA CADA CATEGORIA 1 FUNCAO

	NO CADASTRAR APENAS O USUARIO(ALUNO) SE CADASTRA,
	PARA CADASTRAR O ADMIN É UM INPUT MANUAL NO SISTEMA,
	E PARA CADASTRAR O PROFESSOR, NA TELA DO ADMIN TERÁ UM BOTAO QUE SETA A CATEGORIA EM 1(PROFESSOR) E 2(ADMIN) - IGUAL ECOMMERCE,

	NA TELA DE LOGIN, ELE BUSCA PELO EMAIL SENHA E CATEGORIA, SE CATEGORIA = 0 REDIRECIONA->VISAO_USUARIO , CATEGORIA = 1 REDIRECIONA->VISAO_PROFESSOR E CASO SEJA 2 REDIRECIONA->VISAO_ADMIN 